apiVersion: v1
kind: Pod
metadata:
 name: myApp
 labels:
  app: myApp
spec:
 containers:
 - name: myapp-containers
   image: busybox
   command: ['sh','-c','echo The app is running! && sleep 3600']
 initContainers:
 - name: init-myservice
   image: busybox
   command: ['sh','-c','untill nslookup myservice; do echo waiting for myservice; sleep 2; done;'] 
 - name: init-mydb
   image: busybox
   command: ['sh','-c','untill nslookup mydb; do echo waiting for mydb; sleep 2; done;']
